<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>14</LangVersion>
        <IsPackable>false</IsPackable>

        <OutputType>Library</OutputType>

        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="NUnit" Version="4.5.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LibreTranslate.Net.Enhanced\LibreTranslate.Net.Enhanced.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="textfile.txt" />
      <Content Include="textfile.txt">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
